### ISSUE TITLE
No license attached to this code

### ISSUE THREAD

**Issue by TomMD** [floodyberry/ed25519-donna#24]
It is unclear what this code is licensed under - please clarify.

**Comment by TomMD** [comment]
Ahh, I see individual files are tagged as public domain.  Seeing as at least something was probably borrowed from AGLs code should this also carry the google attribution due to the BSD3 license?

**Comment by floodyberry** [comment]
I'm not quite sure what to put for the license actually. agl's 64 bit version is the only one I have any code from (whatever I contributed to it, and curve25519_contract in my 32/64 bit versions I think), and it is marked as public domain. I don't mind marking the curve25519 code with the Google/BSD3 license, but I can't tell if it's necessary for not?

**Comment by TomMD** [comment]
Honestly I wouldn't have even opened the issue had I had the thought to check the file headers for the license, so I'll just close.  For my purposes I'm using both curve25519-donna and ed25519-donna in order to support scalarmult (ecdh) too so I'll already be carrying the attribution.
