### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nogy** [floodyberry/ed25519-donna#39]
Hi,

I was looking at your code just now but found that it does not name a license? Is this MIT / LGPL / GPL?
Could you detail that so it's more obvious as to how/if it can be used in other projects?

I feel since it leans on https://github.com/agl/curve25519-donna it might use a similar BSD style license as well
https://github.com/agl/curve25519-donna/blob/master/LICENSE.md

Best regards many thanks,

Bastian

**Comment by forthy42** [comment]
Am Freitag, 14. Juli 2023, 10:39:41 CEST schrieb nogy:
> Hi,
> 
> I was looking at your code just now but found that it does not name a
> license? Is this MIT / LGPL / GPL? Could you detail that so it's more
> obvious as to how/if it can be used in other projects?

It is derived from Andrew Moon's (nickname floodyberry) ed25519-donna, so 
please ask there (and you already did).  I'm politely waiting for the answer.

https://github.com/floodyberry/ed25519-donna

> I feel since it leans on https://github.com/agl/curve25519-donna it might
> use a similar BSD style license as well
> https://github.com/agl/curve25519-donna/blob/master/LICENSE.md

His other projects have a LICENSE line in the README, and it is either “MIT or 
public domain” or just “public domain”.  I'm 100% sure it is either of those, 
and he just forgot to write it down somewhere.

-- 
Bernd Paysan
"If you want it done right, you have to do it yourself"
net2o id: ***@***.***}1GWr!+0qqp_Cn176t4(dQ*
https://net2o.de/

**Comment by ryancdotorg** [comment]
> Public domain by Andrew M.

https://github.com/floodyberry/ed25519-donna/blob/master/ed25519.c#L2

**Comment by nogy** [comment]
Thanks a lot.

I missed that comment. I was looking for a license linked in github which most projects have since it is easier to spot.

> > Public domain by Andrew M.
> 
> https://github.com/floodyberry/ed25519-donna/blob/master/ed25519.c#L2
